### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by baktun14** [mlabrum/vsts-download-secure-file#1]
Hi, thanks for making this task. I get an unhandled promise rejection saying:
`Unhandled promise rejection (rejection id: 1): Error: Failed to find api location for area: distributedtask id: adcfd8bc-b184-43ba-bd84-7c8c6a2ff421`

I can't tell yet where this is coming from, but the secure file doesn't get downloaded.

Oh I just realized it works inside a build definition but not a release.

**Comment by mlabrum** [comment]
Ah, I haven't tested this within a release only a build step.
I've found this with that error https://github.com/Microsoft/vso-agent/issues/210 but I find that weird since I'm pulling the rest url directly from the agent https://github.com/mlabrum/vsts-download-secure-file/blob/master/buildtask/index.js#L6

I'll find some time to test that, It could be that I need to add another permission https://github.com/mlabrum/vsts-download-secure-file/blob/master/vss-extension.json#L22 `vso.release` maybe?

**Comment by EwanNoble** [comment]
Having the same issue here, I've tried adding that scope but it didn't appear to fix it.

**Comment by mlabrum** [comment]
I've just uploaded 0.0.8 hopefully this should fix the release issues, thanks @Carl-Hugo
